version: "2.1"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: opensuse
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  clockwork:
    image: calendar-o-o/web
    build:
      dockerfile: docker-files/Dockerfile
      args:
        CONTAINER_USERID: 1000
    command: bundler exec clockwork clock.rb
    volumes:
      - .:/web:z
    depends_on:
      - db
      - redis
  web:
    image: calendar-o-o/web
    build:
      dockerfile: docker-files/Dockerfile
      args:
        CONTAINER_USERID: 1000
    volumes:
      - .:/web:z
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - clockwork
